### ISSUE TITLE
KTorrent - Status and Notification

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#102]
KTorrent on Status and Notification doesn't use symbolic icon.

![Screenshot_20241112_091514](https://github.com/user-attachments/assets/ff699d8c-7848-4f73-87f0-28b38b5f2317)

```
Operating System: openSUSE Tumbleweed 20241109
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Graphics Platform: Wayland
```

P.S. Congratulation, I haven't visited your package for a long time, I see that you have completed it quite well for KDE plasma.

I will use it often now that has accent support. Thank you.

**Comment by SylEleuth** [comment]
I've added missing symbolic icons for several apps. It should be fine (at least for KTorrent).
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/aee2c5a85da2c8a5fc58c2539356c5ce392e8a28
