### ISSUE TITLE
More accent color-schemes support for symbolics/folders? 

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#103]
Fortunately this package support accent color-schemes from wallpaper.

This makes it even more icon-themes-friendly for everyone in latest KDE (wayland) who use this feature.

However, there are some symbolic icons that don't follow wallpaper accent color-schemes.

Right click menu
- Empty File...
- Link to File or Directory...
![Screenshot_20241112_112040](https://github.com/user-attachments/assets/3162fb0a-14b6-492e-a571-7fd787c0e9a4)

Volume Indicator Icon (only on this popup don't follow wallpaper accent color-schemes, on tray volume icon is it all right)
- Mouse Wheel - up/down
![Screenshot_20241112_112229](https://github.com/user-attachments/assets/96fe8de6-42fd-4913-b31a-e8a3c7d7a953)

There must be others symbolics icons that needs accent support or folders like [papirus-colors](https://github.com/varlesh/papirus-colors). Thank you.

**Comment by SylEleuth** [comment]
I've added `empty file` https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/2b075d39960c6895d7c0f04177188ba1144a1ad1

`Link` icon is a messy one. It uses `emblem-symbolic-link` instead of regular `forward` or `link` icon from `actions`. `KDE`, not knowing why, uses `emblem` icons in some weird places, where it could just use normal icons.
I've just made some tests and added it to `actions` and it works. Unfortunately it may lead to some issues in the future, issues that I can't anticipate right now. `Breeze` and `Papirus` omits and neglects that icon (including `empty file`), so until KDE fix that I don't want to touch it.

How do You use accent colour to change colours of the icons? Are You using settings `Global theme` / `Colours`? Because it doesn't do much on my side.

I choose different path for `folders` icons but looking now how it was made I think that I would have to rework what I've already done. Although not now. I want it to be available for different distros and not only KDE, with a script or at least easy way to change the colours. But definitely it has to be done one way or another. I'm not sure when or how I will do it so I won't give You any date.

**Comment by buufmax** [comment]
Saw the fix of empty symbolic icon awesome for providing so fast.

All right regarding Link `emblem-symbolic-link` Thanks for the detailed clarification of this part.

I use Accent color from wallpaper "color-schemes". Watch below the link, Every time the wallpaper changed, the whole background/text of KDE schemes changes too, so do the Icons on symbolic parts, at least the majority, there are some who do not respect it.
[Screencast_20241112_150717.webm](https://github.com/user-attachments/assets/da076c97-cfa6-4490-9a85-3ac65c7643fd)

This settings i use from color-schemes
![Screenshot_20241112_151302](https://github.com/user-attachments/assets/a1ba6419-268a-4cd7-ba68-8b55c5922be1)

Regarding folders color-accent, I see, maybe it's too early for this request, therefore for now you can ignore this request maybe later it can be revised?

**Comment by SylEleuth** [comment]
I've missed the options for accent colours. Now will be easier for me to find the icons. Get back to You with that.

Breeze folder icons are simple and flat. I have nothing against flat icons but in general I'm trying to add some depth wherever I can, very subtle (sometimes not) but nevertheless. That's what I did with folders. But "depth" is different depending the colour and making one version that is easily transformable to different colour and still look good would be tricky.

**Comment by buufmax** [comment]
I'm glad you caught KDE accent settings.

As for breeze icons, in my opinion Suru++ or your gruvbox it is many times better than breeze. I didn't mean to change folders on your packages.

Simply add a code to follow accent colors. Not moving anything else in the structure, existing colors or dimensions.

Breeze follows accent colors for his folders, other icons that do the same are: Colloid-icon-theme (vinceliuice), Tela-icon-theme (vinceliuice), Antu (fabianalexis), Breeze-Round-Chameleon Dark Icons (l4k1).

Always if it's feasible without breaking anything.

**Comment by SylEleuth** [comment]
I'm chasing a volume icons right and wanted to ask one more question: are there more settings for accent colours that You haven't showed me? Whatever colour I choose, icons and texts only got a slight tint and it's nothing like on Your screenshots.

**Comment by buufmax** [comment]
Yeah, the volume icon is fixed now. Thank you.

No, there aren't other settings i use. Only those below, 3rd link Monochrome.colors by pwyde.

![Screenshot_20241114_140503](https://github.com/user-attachments/assets/ca4b77f7-d2d6-439f-845b-004610094206)
[Screencast_20241114_140026.webm](https://github.com/user-attachments/assets/12ef8292-c5e5-4bce-bb6b-9a6232f2a63c)
[Monochrome Waccent-091024.colors.tar.gz](https://github.com/user-attachments/files/17748994/Monochrome.Waccent-091024.colors.tar.gz)


No scripts, or widgets for accents. KDE do it itself without 3rd parts, wallpapers auto changes in min's that i set on KDE Wallpaper Settings.
Choose the option "Accent color from wallpaper", As soon as you change the wallpaper, it will take the main color of the photo.
It should work if you are in Wayland and in a refreshed KDE.

My data
```
Operating System: openSUSE Tumbleweed 20241112
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Graphics Platform: Wayland
```

**Comment by SylEleuth** [comment]
It might be wayland, I'm using X11. Can you get same text and icons effect with `Breeze Dark` for example?

**Comment by buufmax** [comment]
I don't know what to say about X11, i use wayland standalone, but i read that Accents is its wayland feature mostly.

Regarding Breeze-Dark, Yes it can, if [features](https://github.com/SylEleuth/gruvbox-plus-icon-pack/issues/103#issuecomment-2470657886) accents on color scheme are checked then background, text and icons all three will follow the color of wallpaper.

**Comment by SylEleuth** [comment]
I've just logged in on Wayland and it looks the same as on X11. It must be that colors modification by pwyde.

Anyway, I'm closing it now. I will work on folders and release it when it will be ready

Thanks for the help.
