### ISSUE TITLE
Tumbleweed Distro - New Distro Icon

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#104]
Back on Tumbleweed request, they got a [new](https://news.opensuse.org/2024/10/30/tw-monthly-update-october/) distro icon recently.

Please remove the old icon you set on [#63](https://github.com/SylEleuth/gruvbox-plus-icon-pack/issues/63) and replace it with the new one.

On this link you may find the new icon logo.
https://github.com/openSUSE/distribution-logos/tree/main/Tumbleweed

Watch out on the last two.
square-hicolor.svg / square-symbolic.svg.

Icon name hasn't changed "**distributor-logo-Tumbleweed.svg**".

Thank you!

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/73722360a92fc08d8a9955f8a66680e409739588
