### ISSUE TITLE
MacOS would be absolutely wonderful

### ISSUE THREAD

**Issue by nopears** [SylEleuth/gruvbox-plus-icon-pack#108]
If there'd be a way to use those icons on MacOS it would be a really good feature. There is no such directory as icons, but you can simply change the icon of an app manually. So having icons as separate files could be the way to implement it.

**Comment by SylEleuth** [comment]
I've never used MacOS so I have no idea how those icons would look like. I have no plans to do anything for any other systems, those icons are made for linux only, but if You want to use individual icons or even a whole pack in MacOS You can free do that.
