### ISSUE TITLE
KDE - File Associations

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#110]
Very small to reports, but i am doing...

System Settings > Default Applications > File Associations

application
- font-tdpfr
- x-xz

x-content
- ostree-repository

Those names don't use symbolic icons.

```
Operating System: openSUSE Tumbleweed 20241129
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Graphics Platform: Wayland
```

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/7be992c90d23d1b1254f469a118f3dcfe12f1b9e

`Ostree` doesn't have an icon, anything I could find, so I made it a link to something that is at least similar to versioning system
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/bd4ce4d70b324e7954b4d49f572d99eab17b32a9
