### ISSUE TITLE
KDE Recent Files

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#111]
I notice that many icons names appear here as generic executables.

KDE > System Settings > Recent Files

![Screenshot_20241203_170007](https://github.com/user-attachments/assets/c41e1f2a-dec9-4cfe-b243-e79ca103998a)

The apps names aren't random or services without icon name, but internal KDE apps.

Maybe it's a bug? The difference is that the application that starts with a lowercase letter doesn't have relevant icon.

**Comment by SylEleuth** [comment]
Probably a bug. If You compare with a different packs the result will be the same.
