### ISSUE TITLE
Preview Icon

### ISSUE THREAD

**Issue by buufmax** [SylEleuth/gruvbox-plus-icon-pack#113]
On newest master, something is wrong with fourth icon on the Preview.

![Screenshot_20241207_151637](https://github.com/user-attachments/assets/e2d62f3a-f75d-4188-8557-34c5de492855)

Perhaps it have some unnecessary data?

**Comment by SylEleuth** [comment]
I was my mistake. I've uploaded the wrong zip file. It's my own "branch" with a lot of things to test. It should be now the same as git version. Please discard it and use the updated release.

**Comment by buufmax** [comment]
I always get it from `https://github.com/SylEleuth/gruvbox-plus-icon-pack.git`

Same situation on new commits.
[Screencast_20241207_172041.webm](https://github.com/user-attachments/assets/c621392a-a68d-4dae-a5db-4c7d89f7eac4)

**Comment by SylEleuth** [comment]
That messed up icon it's a trash icons from `places/scalable` and the last time I've touched it was... 6 month ago. So I'm not sure what is going on. I've tested it and it looks ok on my side.

**Comment by buufmax** [comment]
The very recent [commits](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/2a3263939cc50b97d5a79f667c00a3c61b2a6441) fixed the trash messed icon on KDE Preview.

![Screenshot_20241216_134618](https://github.com/user-attachments/assets/e5ed75a2-2626-43e9-bfce-a768ee075109)

This is solved :)

P.S. i quite like the folder color changes, now trash have support color scheme, Appreciate a lot if you're working with folders alo following color schemes.
