### ISSUE TITLE
Missing Icon - Live Captions

### ISSUE THREAD

**Issue by Sunspark-007** [SylEleuth/gruvbox-plus-icon-pack#130]
[Repo Link](https://github.com/abb128/LiveCaptions)
[Icon Link](https://github.com/abb128/LiveCaptions/blob/main/data/icons/hicolor/scalable/apps/net.sapples.LiveCaptions.svg)
[Symbolic Icon Link](https://github.com/abb128/LiveCaptions/blob/main/data/icons/hicolor/symbolic/apps/net.sapples.LiveCaptions-symbolic.svg)

```
[Desktop Entry]
Type=Application
Name=Live Captions
Comment=Provides live captioning for desktop and microphone audio
Icon=net.sapples.LiveCaptions
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=livecaptions net.sapples.LiveCaptions
Terminal=false
Categories=Accessibility;GTK;Utility;
Keywords=Closed Captions;Speech to text;Subtitles;Deaf;livecaptions;closedcaptions;stt;asr;microphone;
StartupNotify=true
X-Flatpak=net.sapples.LiveCaptions
```

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/418c954e1982cb118c1ac441351d0daf21356138
