### ISSUE TITLE
Whatsapp symbolic icon is black

### ISSUE THREAD

**Issue by Edd7711** [SylEleuth/gruvbox-plus-icon-pack#136]
Hello, as the title says, whatsapp symbolic icon is totally black, while I think it should be white like other icons.
I'm using a dark theme in kde plasma, here's a screenshot.
![immagine](https://github.com/user-attachments/assets/bc56135c-1165-48e5-8b99-a2fe99234f1d)

**Comment by SylEleuth** [comment]
What I'm looking at? How You did You install the pack?
Those icons are no longer there. `Thunderbird` and `Xournal` look completely different.

**Comment by Edd7711** [comment]
> What I'm looking at? How You did You install the pack? Those icons are no longer there. `Thunderbird` and `Xournal` look completely different.

Installed them in kde settings

**Comment by SylEleuth** [comment]
Uninstall, remove any traces of it (from `~/.local/share/icons`) and install again.

**Comment by Edd7711** [comment]
Just downloaded the last release here on Github, everything fixed.

**Comment by SylEleuth** [comment]
Latest release here is the same as the one on kde store.
