### ISSUE TITLE
Optimized svg output

### ISSUE THREAD

**Issue by mojamuto** [SylEleuth/gruvbox-plus-icon-pack#16]
The icons in the app/16 folder have to be ungrouped, but some icons are grouped by themselves when saved, for example:

the f3d.svg icon, if I save it by unchecking the box create groups for similar attributes:
![01](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/36079583/abaf6d3e-5a89-4354-8422-536a3d5ddf16)
When opening the svg it is ungrouped but the file size is 550 bytes.

However if I save it with the box unchecking the create groups for similar attributes box checked:
![02](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/36079583/3994063e-104a-433b-861c-5b66de83281d)
When you open the svg file it is bundled and the file size is 490 bytes.

Is the priority that they are ungrouped or that they have a smaller size?

**Comment by SylEleuth** [comment]
Grouped and smaller size can work together. Sometimes grouping is desirable if there is a lot of elements. I'd rather have that than list of 50 or more elements. Of course if I'm not grouping myself.
