### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by Chewbaccaun** [SylEleuth/gruvbox-plus-icon-pack#21]
Hey, I downloaded your icon pack and notice that one icon is missing when nautilus file manager is tiny.
![Screenshot from 2023-06-24 23-01-09](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/70461329-ff3b-4d22-b7a9-679862db57da)
![Screenshot from 2023-06-24 23-01-23](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/13c16e7f-6f43-4a2d-9560-9ea8b08a9463)

**Comment by SylEleuth** [comment]
I can't reproduce it on KDE. And I can't make Nautilus to look like on the screenshots. I need more information about DE and theming.

**Comment by Chewbaccaun** [comment]
I am on GNOME 44.2
The theme I use is this: [https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme](url)
I use the theme on Legacy gtk3 apps and linked to Libadwaita for gtk4 apps too.

![Screenshot from 2023-06-25 17-46-40](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/5f4dffbb-b801-4129-b345-6502b999b84a)
![Screenshot from 2023-06-25 17-39-51](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/09cb1106-8a30-498c-8e89-59fd0582e493)
![Screenshot from 2023-06-25 17-39-05](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/529c5874-599f-4eec-adc7-836a4e413d30)

**Comment by SylEleuth** [comment]
Thank you. In the meantime could You tell me:
1. What kind of app is hiding under Arch icon on the dock?
2. VSCode has no proper icon? Is it regular Code app? Can you provide .desktop info for it?
3. What is the app on the dock first on the right?

**Comment by Chewbaccaun** [comment]
1. This is my [Distrobox](https://github.com/89luca89/distrobox) Arch container, I had to put an icon manually because even the default entry doesn't have an icon, so I think it's not a bug from this pack. (already fixed myself)
2. This VS Code with the default icon isn't the flatpak version, I downloaded it from the official [.RPM](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions).
![Screenshot from 2023-06-26 13-04-49](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/7572bd07-f52b-411b-8b2d-95ebcc82e584)

3. This is the icon that the "Show Apps" button from the [dock](https://extensions.gnome.org/extension/307/dash-to-dock/) is picking.
![Screenshot from 2023-06-26 13-08-44](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/86445165/3d2441aa-c1df-4061-9907-2700b11ecad9)

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/61c91f9020a42e417c40400c9ab64d8c01506479
