### ISSUE TITLE
option to change folder colors

### ISSUE THREAD

**Issue by guillopacheco** [SylEleuth/gruvbox-plus-icon-pack#22]
Hello. I just installed these icon pack, its great thank you. I have an issue trying to change the folders, in gnome the default color for the folders are blue. How can I change the folders to the golden ones found inside the icon pack?

**Comment by guillopacheco** [comment]
i'm sorry, I kept looking and found this file browser extension, at least its not 1 folder at a time. https://github.com/costales/folder-color

**Comment by SylEleuth** [comment]
That set of scripts are only usable for specific file managers. There is a plan to make a way to change folders colors globally. Each file named `folder-*.svg` is actually a soft link to a specific file. Currently it links to `folder-blue-*.svg`, so it shouldn't be hard to just change that symlink path to a different folder with a different color. I can't make that kind of script right now but it should be in pack. Maybe someone else will find some time and do it.

**Comment by Clemovski** [comment]
Hello.

This is the quick and dirty script I have made to replace my folder colors. You just have to replace highland with the color of your choice, give it execution privileges, and launch it from ~/.icons/gruvbox-plus-icon-pack-5.5.0/places/scalable .
Hope it will help someone in the future.

Note that bookmark folders do not have color variants.

<details>
<summary>Click to expand</summary>
#!/usr/bin/env bash

rm certificate-server.svg
ln -s folder-highland-locked.svg certificate-server.svg
rm desktop.svg
ln -s user-highland-desktop.svg desktop.svg
rm document-open-recent.svg
ln -s folder-highland-recent.svg document-open-recent.svg
rm edittrash.svg
ln -s user-trash-full.svg edittrash.svg
rm emptytrash.svg
ln -s user-trash.svg emptytrash.svg
rm folder-activities.svg
ln -s folder-highland-activities.svg folder-activities.svg
rm folder-apple.svg
ln -s folder-highland-apple.svg folder-apple.svg
rm folder-apps.svg
ln -s folder-highland-apps.svg folder-apps.svg
rm folder-atom.svg
ln -s folder-highland-atom.svg folder-atom.svg
rm folder-camera.svg
ln -s folder-photo.svg folder-camera.svg
rm folder-cd.svg
ln -s folder-highland-cd.svg folder-cd.svg
rm folder-cinnamon.svg
ln -s folder-highland-cinnamon.svg folder-cinnamon.svg
rm folder-cloud.svg
ln -s folder-highland-mail-cloud.svg folder-cloud.svg
rm folder-decrypted.svg
ln -s folder-unlocked.svg folder-decrypted.svg
rm folder-desktop.svg
ln -s user-highland-desktop.svg folder-desktop.svg
rm folder-development.svg
ln -s folder-highland-development.svg folder-development.svg
rm folder-docker.svg
ln -s folder-highland-docker.svg folder-docker.svg
rm folder-documents-open.svg
ln -s folder-highland-documents-open.svg folder-documents-open.svg
rm folder-documents.svg
ln -s folder-highland-documents.svg folder-documents.svg
rm folder-download-open.svg
ln -s folder-highland-download-open.svg folder-download-open.svg
rm folder-downloads.svg
ln -s folder-highland-download.svg folder-downloads.svg
rm folder-download.svg
ln -s folder-highland-download.svg folder-download.svg
rm folder-drag-accept.svg
ln -s folder-highland-drag-accept.svg folder-drag-accept.svg
rm folder-dropbox.svg
ln -s folder-highland-dropbox.svg folder-dropbox.svg
rm folder-electron.svg
ln -s folder-highland-electron.svg folder-electron.svg
rm folder-encrypted.svg
ln -s folder-highland-locked.svg folder-encrypted.svg
rm folder-favorites.svg
ln -s folder-highland-favorites.svg folder-favorites.svg
rm folder-finder.svg
ln -s folder-highland-mac.svg folder-finder.svg
rm folder-fonts.svg
ln -s folder-highland-fonts.svg folder-fonts.svg
rm folder-games.svg
ln -s folder-highland-games.svg folder-games.svg
rm folder-gdrive.svg
ln -s folder-highland-google-drive.svg folder-gdrive.svg
rm folder-github.svg
ln -s folder-highland-github.svg folder-github.svg
rm folder-gitlab.svg
ln -s folder-highland-gitlab.svg folder-gitlab.svg
rm folder-git.svg
ln -s folder-highland-git.svg folder-git.svg
rm folder-gnome.svg
ln -s folder-highland-gnome.svg folder-gnome.svg
rm folder-google-drive.svg
ln -s folder-highland-google-drive.svg folder-google-drive.svg
rm folder-home.svg
ln -s user-home.svg folder-home.svg
rm folder_home.svg
ln -s user-home.svg folder_home.svg
rm folder-html.svg
ln -s folder-network.svg folder-html.svg
rm folder-icons.svg
ln -s folder-highland-icons.svg folder-icons.svg
rm folder-image-people.svg
ln -s folder-highland-image-people.svg folder-image-people.svg
rm folder-images.svg
ln -s folder-highland-pictures.svg folder-images.svg
rm folder-image.svg
ln -s folder-highland-pictures.svg folder-image.svg
rm folder-important.svg
ln -s folder-highland-important.svg folder-important.svg
rm folder-java.svg
ln -s folder-highland-java.svg folder-java.svg
rm folder-linux.svg
ln -s folder-highland-linux.svg folder-linux.svg
rm folder-locked.svg
ln -s folder-highland-locked.svg folder-locked.svg
rm folder-mac.svg
ln -s folder-highland-mac.svg folder-mac.svg
rm folder-mail-cloud.svg
ln -s folder-highland-mail-cloud.svg folder-mail-cloud.svg
rm folder-mail.svg
ln -s folder-highland-mail.svg folder-mail.svg
rm folder-mega.svg
ln -s folder-highland-mega.svg folder-mega.svg
rm folder-meocloud.svg
ln -s folder-highland-meocloud.svg folder-meocloud.svg
rm folder-mozilla.svg
ln -s folder-highland-mozilla.svg folder-mozilla.svg
rm folder-music-open.svg
ln -s folder-highland-music-open.svg folder-music-open.svg
rm folder-music.svg
ln -s folder-highland-music.svg folder-music.svg
rm folder-network.svg
ln -s folder-highland-network.svg folder-network.svg
rm folder-open-recent.svg
ln -s folder-recent.svg folder-open-recent.svg
rm folder-open.svg
ln -s folder-highland-open.svg folder-open.svg
rm folder_open.svg
ln -s folder-open.svg folder_open.svg
rm folder-owncloud.svg
ln -s folder-highland-owncloud.svg folder-owncloud.svg
rm folder-pcloud.svg
ln -s folder-highland-pcloud.svg folder-pcloud.svg
rm folder-photos.svg
ln -s folder-photo.svg folder-photos.svg
rm folder-photo.svg
ln -s folder-highland-photo.svg folder-photo.svg
rm folder-pictures-open.svg
ln -s folder-highland-pictures-open.svg folder-pictures-open.svg
rm folder-pictures.svg
ln -s folder-highland-pictures.svg folder-pictures.svg
rm folder-picture.svg
ln -s folder-highland-pictures.svg folder-picture.svg
rm folder-print.svg
ln -s folder-highland-print.svg folder-print.svg
rm folder-private.svg
ln -s folder-highland-private.svg folder-private.svg
rm folder-publicshare-open.svg
ln -s folder-highland-publicshare-open.svg folder-publicshare-open.svg
rm folder-publicshare.svg
ln -s folder-highland-image-people.svg folder-publicshare.svg
rm folder-public.svg
ln -s folder-publicshare.svg folder-public.svg
rm folder-recent.svg
ln -s folder-highland-recent.svg folder-recent.svg
rm folder-remote-ftp.svg
ln -s folder-remote.svg folder-remote-ftp.svg
rm folder-remote-nfs.svg
ln -s folder-remote.svg folder-remote-nfs.svg
rm folder-remote-open.svg
ln -s folder-highland-remote-open.svg folder-remote-open.svg
rm folder-remote-smb.svg
ln -s folder-remote.svg folder-remote-smb.svg
rm folder-remote-ssh.svg
ln -s folder-remote.svg folder-remote-ssh.svg
rm folder-remote.svg
ln -s folder-highland-remote.svg folder-remote.svg
rm folder-saved-search.svg
ln -s folder-highland-saved-search.svg folder-saved-search.svg
rm folder-script.svg
ln -s folder-highland-script.svg folder-script.svg
rm folder-sound.svg
ln -s folder-highland-music.svg folder-sound.svg
rm folder-steam.svg
ln -s folder-highland-steam.svg folder-steam.svg
rm folder.svg
ln -s folder-highland.svg folder.svg
rm folder-tar.svg
ln -s folder-highland-tar.svg folder-tar.svg
rm folder-templates-open.svg
ln -s folder-highland-templates-open.svg folder-templates-open.svg
rm folder-templates.svg
ln -s folder-highland-templates.svg folder-templates.svg
rm folder-temp.svg
ln -s folder-recent.svg folder-temp.svg
rm folder-text.svg
ln -s folder-highland-documents.svg folder-text.svg
rm folder-themes.svg
ln -s folder-highland-themes.svg folder-themes.svg
rm folder-torrent.svg
ln -s folder-highland-torrent.svg folder-torrent.svg
rm folder-txt.svg
ln -s folder-highland-documents.svg folder-txt.svg
rm folder-unlocked.svg
ln -s folder-highland-unlocked.svg folder-unlocked.svg
rm folder-vbox.svg
ln -s folder-highland-vbox.svg folder-vbox.svg
rm folder-videocamera.svg
ln -s folder-video.svg folder-videocamera.svg
rm folder-videos-open.svg
ln -s folder-highland-videos-open.svg folder-videos-open.svg
rm folder-videos.svg
ln -s folder-video.svg folder-videos.svg
rm folder-video.svg
ln -s folder-highland-video.svg folder-video.svg
rm folder-virtual.svg
ln -s folder-remote.svg folder-virtual.svg
rm folder-visiting.svg
ln -s folder-highland-visiting.svg folder-visiting.svg
rm folder-vscode.svg
ln -s folder-highland-vscode.svg folder-vscode.svg
rm folder-wifi.svg
ln -s folder-highland-wifi.svg folder-wifi.svg
rm folder-windows.svg
ln -s folder-highland-wine.svg folder-windows.svg
rm folder-wine.svg
ln -s folder-highland-wine.svg folder-wine.svg
rm folder-yandex-disk.svg
ln -s folder-highland-yandex-disk.svg folder-yandex-disk.svg
rm gnome-dev-trash-empty.svg
ln -s user-trash.svg gnome-dev-trash-empty.svg
rm gnome-dev-trash-full.svg
ln -s user-trash-full.svg gnome-dev-trash-full.svg
rm gnome-fs-directory-accept.svg
ln -s folder-open.svg gnome-fs-directory-accept.svg
rm gnome-fs-directory.svg
ln -s folder.svg gnome-fs-directory.svg
rm gnome-fs-home.svg
ln -s user-home.svg gnome-fs-home.svg
rm gnome-fs-trash-empty-accept.svg
ln -s user-trash-full.svg gnome-fs-trash-empty-accept.svg
rm gnome-fs-trash-empty.svg
ln -s user-trash.svg gnome-fs-trash-empty.svg
rm gnome-fs-trash-full.svg
ln -s user-trash-full.svg gnome-fs-trash-full.svg
rm gnome-home.svg
ln -s user-home.svg gnome-home.svg
rm gnome-stock-trash-empty.svg
ln -s user-trash.svg gnome-stock-trash-empty.svg
rm gnome-stock-trash-full.svg
ln -s user-trash-full.svg gnome-stock-trash-full.svg
rm gnome-stock-trash.svg
ln -s user-trash.svg gnome-stock-trash.svg
rm gtk-directory.svg
ln -s folder.svg gtk-directory.svg
rm inode-directory.svg
ln -s folder.svg inode-directory.svg
rm insync-folder.svg
ln -s folder-highland-google-drive.svg insync-folder.svg
rm knetattach.svg
ln -s folder-remote.svg knetattach.svg
rm library-music.svg
ln -s folder-highland-music.svg library-music.svg
rm network.svg
ln -s folder-network.svg network.svg
rm network-workgroup.svg
ln -s folder-highland-network.svg network-workgroup.svg
rm repository.svg
ln -s folder-network.svg repository.svg
rm stock_folder.svg
ln -s folder.svg stock_folder.svg
rm stock_open.svg
ln -s folder-open.svg stock_open.svg
rm stock_trash_empty.svg
ln -s user-trash.svg stock_trash_empty.svg
rm stock_trash_full.svg
ln -s user-trash-full.svg stock_trash_full.svg
rm trashcan_empty.svg
ln -s user-trash.svg trashcan_empty.svg
rm trashcan_full.svg
ln -s user-trash-full.svg trashcan_full.svg
rm user-desktop.svg
ln -s user-highland-desktop.svg user-desktop.svg
rm user-home-open.svg
ln -s user-highland-home-open.svg user-home-open.svg
rm user-home.svg
ln -s user-highland-home.svg user-home.svg
rm xfce-trash_empty.svg
ln -s user-trash.svg xfce-trash_empty.svg
rm xfce-trash_full.svg
ln -s user-trash-full.svg xfce-trash_full.svg
</details>
