### ISSUE TITLE
[Icon Request] Qubes OS (Xen/Linux Distribution)

### ISSUE THREAD

**Issue by Cyanide-1** [SylEleuth/gruvbox-plus-icon-pack#23]
Please add Qubes OS icon? thanks!

**Information**

* **Icon Name:** distributor-logo-qubes

* **Website:** https://www.qubes-os.org/

* **Description:** "A reasonably secure operating system."

* **Reference Pictures:** https://www.qubes-os.org/doc/visual-style-guide/#logos

![qubes-logo](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/136278181/adb1a8c9-597d-48db-9286-4b8e2e187de2)
![qubes-logo-2000x-2150x](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/136278181/599710d7-56a7-4dfe-a43d-9179193adbb0)

**Comment by Cyanide-1** [comment]
i would appreciate it if you added this icon to the icon pack! thank you!

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/1cd32b1af49903ce57c95bc8a37bd65430ea43ec

**Comment by Cyanide-1** [comment]
Thanks! i appreciate it a lot :3
