### ISSUE TITLE
asociate icon to file type

### ISSUE THREAD

**Issue by guillopacheco** [SylEleuth/gruvbox-plus-icon-pack#25]
Hello. I have a problem with some 3D file types (.3ds. stl .obj .3mf...) in gnome these filestypes are not asociated with the icon found in the icon pack. How can I assign the icon to all the files, not one by one ? in kde its easier, but in gnome the info its not clear. thank you!

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/50977450/7ab67b71-8a6e-40b2-8b1b-b7599a6bdc17)

**Comment by SylEleuth** [comment]
Unfortunately this is a Gnome problem and I can't do anything with that. I'm sorry.
