### ISSUE TITLE
Missing a lot of symbolic icons

### ISSUE THREAD

**Issue by Gold3nF3nix** [SylEleuth/gruvbox-plus-icon-pack#28]
![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/75486623/2a9f69c1-92d5-4275-afcb-d9bdac2f185f)

**Comment by SylEleuth** [comment]
I have no idea what I'm looking at.

**Comment by Gold3nF3nix** [comment]
Tokodon

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack#contribution

**Comment by SylEleuth** [comment]
All icons are there and the problem is with Tokodon itself.
https://bugs.kde.org/show_bug.cgi?id=479334
