### ISSUE TITLE
Missing "favorite" icon in GNOME 45 Files (Nautilus)

### ISSUE THREAD

**Issue by alichtman** [SylEleuth/gruvbox-plus-icon-pack#32]
![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/20600565/9d68ffcb-25c9-4415-89f8-66b92e47d7ce)

All the way on the right, the icon to favorite / unfavorite (an empty star, and a filled star) is missing. Interestingly, the "missing icon" icon animates when you click it.

https://apps.gnome.org/Nautilus/

Also: this icon pack is awesome! Thanks :)

**Comment by SylEleuth** [comment]
There are a lot of icons waiting for a final review before adding to the repository. https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f20d6e27371205760e0f0f2462b10803712dd750 were one of them. It should work now.

**Comment by alichtman** [comment]
Just pulled -- can confirm this fix!
