### ISSUE TITLE
GNOME Settings Dropdown Panel Missing Three Icons

### ISSUE THREAD

**Issue by alichtman** [SylEleuth/gruvbox-plus-icon-pack#33]
![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/20600565/c0be1748-9771-42de-98dc-0b4ad42a70a9)

- Top left is supposed to be a screenshot / camera icon.
- Second from right is supposed to be a lock icon.
- Dark Mode icon is missing

I unfortunately don't have links to the SVGs or time to fix it myself.

**Comment by SylEleuth** [comment]
I've added camera and style icons to the repo, but lock icon was already present (at least on my vm gnome). I browsed through different icon packs and found one additional lock icon that might change something. Please pull and see if it changed anything.

**Comment by alichtman** [comment]
All good now! Thanks :)
