### ISSUE TITLE
[icon request] Librewolf

### ISSUE THREAD

**Issue by Mr-Bajs** [SylEleuth/gruvbox-plus-icon-pack#34]
**Description:** A privacy focused desktop web browser based on Firefox.
**Website:** https://librewolf.net/
**Source code:** https://codeberg.org/librewolf

**Icon:** https://codeberg.org/librewolf/branding/src/branch/master/icon/icon.svg
**Icon (transparent):** https://codeberg.org/librewolf/branding/src/branch/master/icon/icon_transparent.svg

**xprop output:**

XKLAVIER_STATE(INTEGER) = 0, 353216512
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 30, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x4600208
		bitmap id # of mask for icon: 0x460020e
		window id # of group leader: 0x4600001
_GTK_THEME_VARIANT(UTF8_STRING) = 
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_WINDOW_ROLE(STRING) = "browser"
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
	                                                
	                 ░░░░░░░                        
	              ░░▒░░░░░░░                        
	            ░▒▒▒▒░░░░░░░        ░░░             
	           ░▒▒▒▒▒░░░░░░        ░░░░░            
	         ░▒▒▒▒▒▒▒░░             ░░░░░           
	        ░▒▒▒▒▒▒░                 ░░░░           
	       ░▒▒▒▒▒░                    ░░░           
	      ░▒▒▒▒▒░                       ░           
	     ░▒▒▒▒▒                                     
	     ▒▒▒▒▒                                      
	    ▒▒▒▒▒                                       
	   ░▒▒▒▒░                                       
	   ▒▒▒▒▒                         ░              
	  ░▒▒▒▒                         ░░              
	  ▒▒▒▒░                       ░░░░              
	  ▒▒▒▒                       ░░░░░░             
	 ░▒▒▒▒                     ░░░░░░░              
	 ▒▒▒▒░                   ░░░░░░░░░              
	 ▒▒▒▒                ░░░░░░░░░░░░░░░░           
	 ▒▒▒▒               ░░░  ░░░░░░░░░░░░           
	 ▒▒▒▒              ░░░░ ░░░░░░░░░░░░░           
	░▒▒▒▒         ░░░░░░░░░░░░░░░░░░░░░░            
	░▒▒▒▒       ░▒▒▒▒░░░░░░░░░░░░░░░░░░             
	░▒▒▒▒        ▒▒▒▒░░░░░░░░░░░░░░░░░              
	░▒▒▒▒        ░▒▒▒░░░░░░░░░░░░░░░░               
	 ▒▒▒▒         ░▒▒░░░░░░░░░░░░░░░                
	 ▒▒▒▒          ▒▒░░░░░░░░░░░░░░░                
	 ▒▒▒▒         ░▒▒░░░░░░░░░░░░░░                 
	 ▒▒▒▒░        ▒▒▒░░░░░░░░░░░░░░                 
	 ░▒▒▒▒       ░▒▒▒░░░░░░░░░░░░░                  
	  ▒▒▒▒      ░▒▒▒▒░░░░░░░░░░░░░                  
	  ▒▒▒▒░     ▒▒▒▒▒░░░░░░░░░░░░                   
	  ░▒▒▒▒    ▒▒▒▒▒▒░░░░░░░░░░░░                   
	   ▒▒▒▒▒  ░▒▒▒▒▒▒░░░░░░░░░░░░                   
	   ░▒▒▒▒░░▒▒▒▒▒▒▒░░░░░░░░░░░░                   
	    ▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░                   
	     ▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░                   
	     ░▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░                   
	      ░▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░        ░           
	       ░▒▒▒▒▒▒▒▒▒░░░░░░░░░░░       ░░           
	        ░▒▒▒▒▒▒▒▒░░░░░░░░░░      ░░░░           
	         ░▒▒▒▒▒▒▒░░░░░░░░░░   ░░░░░░░           
	           ░▒▒▒▒▒░░░░░░░░░░░░░░░░░░░            
	            ░▒▒▒▒░░░░░░░░░░░░░░░░░░             
	              ░░▒░░░░░░░░░░░░░░░░               
	                 ░░░░░░░░░░░░░                  
	                                                

_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 1600, 913
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 73400838, 73400839
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4600205
WM_CLIENT_LEADER(WINDOW): window id # 0x4600001
WM_LOCALE_NAME(STRING) = "sv_SE.UTF-8"
WM_CLIENT_MACHINE(STRING) = "Computer"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 450 by 120
		program specified maximum size: 16384 by 16384
		program specified base size: 450 by 120
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "Navigator", "LibreWolf"
WM_ICON_NAME(STRING) = "LibreWolf"
_NET_WM_ICON_NAME(UTF8_STRING) = "LibreWolf"
WM_NAME(STRING) = "LibreWolf"
_NET_WM_NAME(UTF8_STRING) = "LibreWolf"

**Comment by SylEleuth** [comment]
Done https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/715fd56269c60467a88cf3c3ec18474a76d87b25.
