### ISSUE TITLE
Bottles icon

### ISSUE THREAD

**Issue by alexiscent** [SylEleuth/gruvbox-plus-icon-pack#37]
The icons for [Bottles](https://usebottles.com/) are already present, but are named `com.github.mirkobrombin.bottles` while Flathub installation searches for `com.usebottles.bottles`.

**Comment by SylEleuth** [comment]
I've changed the name, but left the old just in case. Now it also matches the original one's look (only changed colours to gruvbox palette). I've also added some other related missing icons.
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f26fc4b282112f07f8502a123c76dfabeee5d74d
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f908418dd054ffbf9d8e6f9bbd79b6909c598406
