### ISSUE TITLE
Xfce4 icons problem

### ISSUE THREAD

**Issue by mojamuto** [SylEleuth/gruvbox-plus-icon-pack#4]
Hello, the xfce icons such as thunar, mousepad, parole and ristretto, do not use the icon of this theme, looking at the .desktop files of these programs, they all have a name like Icon=org.xfce.mousepad, if I rename to icon=mousepad it fixes.

Is this intentional and do I have to change the .desktop of those programs or is it a bug? thank you

**Comment by SylEleuth** [comment]
Indeed there are no org.xfce.* icons in the pack. I will install xfce and look into it. Thanks.

**Comment by SylEleuth** [comment]
I've added missing icons. It looks ok on my side. It's not all, but other icons with "xfce" in name might be obsolete. I will add them later anyway just for backward compatibility. But for now that should suffice.
Could You test it and tell me if something is missing? I have installed only base apps.

**Comment by mojamuto** [comment]
Of course, I'm going to try it and look more closely for the missing ones, thank you very much

**Comment by mojamuto** [comment]
Everything works fine, after deleting the .icon-theme.cache file

**Comment by mojamuto** [comment]
After clearing the .icon-theme.cache, the icons work, but when doing:
gtk-update-icon-cache -f -t /.local/share/icons/gruvbox-plus-icon-pack 
i get this output: 
gtk-update-icon-cache: The generated cache was invalid.

P.S: I don't know if you prefer that there will be a new problem, instead of reopening the same one, I'm sorry if it's not like that

**Comment by SylEleuth** [comment]
As far as I remember I've never got a valid info after updating the cache so don't stress about it. I will add a new one soon.

**Comment by mojamuto** [comment]
I don't care about the warning, I just wanted to let you know in case you didn't know, I'll close the problem then, thanks again, I really like these icons
