### ISSUE TITLE
Change bookmark icon in GNOME Files

### ISSUE THREAD

**Issue by TXort** [SylEleuth/gruvbox-plus-icon-pack#40]
![missing](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/46675337/1d69c621-8885-41c5-ad81-fe62d41bc5be)

I am not sure if this is actually an existing icon or a missing one, but it looks out of place.

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/53a04aba185a96b9594e2203e253c741b22fa2ce
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/3502e5576a6eb413d9aa4836d3fef2dcd0d57210
