### ISSUE TITLE
Icon request: Obsidian

### ISSUE THREAD

**Issue by Velho-P** [SylEleuth/gruvbox-plus-icon-pack#41]
Program: Obsidian
Site and SVG: https://obsidian.md/blog/new-obsidian-icon/

xprop:

> _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0xa6e3bc00
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = 
_NET_WM_USER_TIME(CARDINAL) = 6362289
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 319, 188
		program specified minimum size: 200 by 150
		program specified maximum size: 2147483647 by 2147483647
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
WM_NAME(UTF8_STRING) = "Nova aba - Obsidian - Obsidian v1.5.8"
_NET_WM_NAME(UTF8_STRING) = "Nova aba - Obsidian - Obsidian v1.5.8"
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "obsidian", "obsidian"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 16144
WM_CLIENT_MACHINE(STRING) = "VelhoPC"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST

Thank you!

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/038ce63ebc7a0f07f36e07aed9589a9e3baa4b3f
