### ISSUE TITLE
Icon request: Easy Effects

### ISSUE THREAD

**Issue by Velho-P** [SylEleuth/gruvbox-plus-icon-pack#44]
Program: Easy Effects
Site: https://github.com/wwmm/easyeffects
SVG: https://github.com/wwmm/easyeffects/blob/master/data/com.github.wwmm.easyeffects.svg
xprop:
> _GTK_FRAME_EXTENTS(CARDINAL) = 34, 34, 26, 42
> _GTK_THEME_VARIANT(UTF8_STRING) = "dark"
> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x19a75c00
> _NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
> _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
> _NET_WM_DESKTOP(CARDINAL) = 0
> _NET_WM_STATE(ATOM) = 
> WM_HINTS(WM_HINTS):
> 		Client accepts input or input focus: True
> 		Initial state is Normal State.
> 		bitmap id # to use for icon: 0x160000a
> 		bitmap id # of mask for icon: 0x1600015
> 		window id # of group leader: 0x1600002
> _NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 	████████████████████████████████████████████████████████████████████████████████████████████████
> 
> 
> _GTK_WINDOW_OBJECT_PATH(UTF8_STRING) = "/com/github/wwmm/easyeffects/window/1"
> _GTK_APPLICATION_OBJECT_PATH(UTF8_STRING) = "/com/github/wwmm/easyeffects"
> _GTK_UNIQUE_BUS_NAME(UTF8_STRING) = ":1.20"
> _GTK_APPLICATION_ID(UTF8_STRING) = "com.github.wwmm.easyeffects"
> _NET_WM_OPAQUE_REGION(CARDINAL) = 46, 26, 709, 12, 34, 38, 733, 337, 46, 375, 709, 12
> _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
> XdndAware(ATOM) = BITMAP
> _NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 23068678, 23068679
> _NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1600005
> WM_CLIENT_LEADER(WINDOW): window id # 0x1600002
> _NET_WM_PID(CARDINAL) = 1010
> WM_LOCALE_NAME(STRING) = "pt_BR.UTF-8"
> WM_CLIENT_MACHINE(STRING) = "VelhoPC"
> WM_NORMAL_HINTS(WM_SIZE_HINTS):
> 		program specified minimum size: 801 by 396
> WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
> WM_CLASS(STRING) = "easyeffects", "easyeffects"
> WM_ICON_NAME(STRING) = "Easy Effects"
> _NET_WM_ICON_NAME(UTF8_STRING) = "Easy Effects"
> WM_NAME(STRING) = "Easy Effects"
> _NET_WM_NAME(UTF8_STRING) = "Easy Effects"

Thank you very much!

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/5ef83f0d8fccce38e652f88de2dea1bfd15fb290
