### ISSUE TITLE
Icons missing in thunar

### ISSUE THREAD

**Issue by Velho-P** [SylEleuth/gruvbox-plus-icon-pack#45]
I upgraded to 5.2 and 2 icons disappeared from thunar:
![missingicons](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/159920579/b11f342d-e891-4769-a0a6-366ae0bd1f69)

My home folder and recent folder

I'm on XFCE 4.18
Thunar 4.18.10

Any idea how can I fix it?

Thank you

**Comment by SylEleuth** [comment]
So far I can't reproduce it. All icons are there on my Arch installation and on Debian in vm. Tomorrow I will install XFCE an check there but I'm not sure it would change anything. In the mean time can You use git repo instead of the package?

**Comment by Velho-P** [comment]
I just did, ran thunar from terminal and got this:
`(thunar:31577): Gtk-WARNING **: 16:42:46.582: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
`
Maybe i did something wrong?

**Comment by Velho-P** [comment]
I just did a fresh install and everything worked!
