### ISSUE TITLE
Rendering issue of some icons

### ISSUE THREAD

**Issue by Edd7711** [SylEleuth/gruvbox-plus-icon-pack#47]
Hello SylEleuth,
idk if that's the right place to ask, btw... I recently re-installed Arch Linux with kde plasma, and I tried to download your icon pack. The problem is that many icons seem rendering incorrectly. I'm saying that since I remember using the icon pack before reinstalling Arch, and i remember a "lighter" black in the backgrounds and other elements (I can see that also by comparing my icons with the ones displayed in the README).
![1](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/92402695/eab15480-32c0-401f-b3c1-ec20e510e677)

**Comment by SylEleuth** [comment]
I assume it's the KDE. What version You installed? Can You try with previous one? I can't reproduce it.

**Comment by Edd7711** [comment]
Yeah they're showing like this everywhere in the system. I'll try previous versions

**Comment by Edd7711** [comment]
Yeah I can install them, they're working and rendering

**Comment by SylEleuth** [comment]
I forgot I have plasma 6 on my laptop. I can see there is a problem, but only with some of scalable icons. Monochromes are all ok. That is extremely weird behaviour.
I will look into it, might take some time. Sorry for that.

**Comment by Edd7711** [comment]
Thank you, no problem! I'll be happy to wait, take you time.

**Comment by thisKnull** [comment]
And, I have also observed that
1. chromium can't be opened as wayland, only xwayland can be used
2. okular cannot be opened
3. Shutdown, reboot, and logout in the start menu are very slow.
All of these do not appear when using the breeze icon.

**Comment by SylEleuth** [comment]
I've eradicated every _blur_ element that I and my friends `find` and `grep` could find. It should be mostly fine, except small things that were related to the blur, e.g. solid elements misplaced or ending in the wrong places. But those won't be visible without max zooming it in Inkscape. I will fix it in the future but for now it's not a priority.

**Comment by Edd7711** [comment]
You're a legend, thanks!
