### ISSUE TITLE
Add icons for NetworkManager

### ISSUE THREAD

**Issue by Diaoul** [SylEleuth/gruvbox-plus-icon-pack#56]
From running nm-applet and switching network I have those errors:

> [2024-05-05 18:16:57.489] [error] Item 'nm-applet': Could not find an icon named 'nm-no-connection-secure' and no pixmap given.
> [2024-05-05 18:16:57.507] [error] Item 'nm-applet': Could not find an icon named 'nm-no-connection-secure' and no pixmap given.
> [2024-05-05 18:16:57.602] [error] Item 'nm-applet': Could not find an icon named 'nm-no-connection-secure' and no pixmap given.
> [2024-05-05 18:16:57.702] [error] Item 'nm-applet': Could not find an icon named 'nm-no-connection-secure' and no pixmap given.
> [2024-05-05 18:16:57.758] [error] Item 'nm-applet': Could not find an icon named 'nm-no-connection-secure' and no pixmap given.
> [2024-05-05 18:16:57.776] [error] Item 'nm-applet': Could not find an icon named 'nm-stage01-connecting04-secure' and no pixmap given.
> [2024-05-05 18:16:57.805] [error] Item 'nm-applet': Could not find an icon named 'nm-stage02-connecting05-secure' and no pixmap given.
> [2024-05-05 18:16:57.822] [error] Item 'nm-applet': Could not find an icon named 'nm-stage02-connecting06-secure' and no pixmap given.
> [2024-05-05 18:16:57.917] [error] Item 'nm-applet': Could not find an icon named 'nm-stage02-connecting07-secure' and no pixmap given.
> [2024-05-05 18:16:58.008] [error] Item 'nm-applet': Could not find an icon named 'nm-stage02-connecting09-secure' and no pixmap given.
> [2024-05-05 18:16:58.034] [error] Item 'nm-applet': Could not find an icon named 'nm-stage03-connecting10-secure' and no pixmap given.
> [2024-05-05 18:16:58.092] [error] Item 'nm-applet': Could not find an icon named 'nm-no-connection-secure' and no pixmap given.

I think some icons are missing to have a nice icon transition. Could you add them? :pray:

**Comment by SylEleuth** [comment]
Indeed there are no icons with those names. But also I couldn't find them [here](https://gitlab.gnome.org/GNOME/network-manager-applet). They just don't exist. There is `nm-no-connection` but no `nm-no-connection-secure`. Same with `nm-stage01-connecting01`  (with different numbers) but no icons ending `-secure`. I've check the code and there are no references to those icons.

`nm-stage` icons are for animation. What's interesting none of the icon packs I've checked have them. In theory I could create them from scratch but I have no idea how to test if they work properly. And the original ones are png so no direct reference (size, shape).

 It might be an error on the software side, or app somehow adds `-secure` to some icons but to be honest I have no idea what is going on. And what about `nm-stage01-connecting01-secure`? Why just few icons missing? If it's animation it should be all. What am I missing?

Do You actually see that those icons are missing or is it just terminal output?

**Comment by Diaoul** [comment]
> Do You actually see that those icons are missing or is it just terminal output?

Hard to say for sure as it's when switching connection 😅 I think yes there is a small glitch during a short period of time when I'm switching.

> And what about nm-stage01-connecting01-secure? Why just few icons missing? If it's animation it should be all. What am I missing?

Maybe it just goes too fast to actually show this part? IDK to be honest.

> but no icons ending `-secure`

The secure bit is probably coming from my VPN connection being on, this creates a small lock on the bottom right corner usually, I can try without and see if I can reproduce without the `-secure` bit but I'm pretty confident this is the reason.

**Comment by SylEleuth** [comment]
There is a line in `applet.c`:
```
#ifdef WITH_APPINDICATOR
    if (INDICATOR_ENABLED (applet))
        icon_name = icon_name_free = g_strdup_printf ("%s-secure", app_indicator_get_icon (applet->app_indicator));
#endif /* WITH_APPINDICATOR */
```
It's the only trace of `-secure` suffix. Does it mean that icon name will have added `-secure` when indicator is enabled? What's the point of that if there are no icons with that name? One thing would be to remove that line, compile it and see if that helps (animation is visible). If the problem is also present while other icon packs are in use then I believe the better place would be asking on the app's gitlab page (linked above).

**Comment by Diaoul** [comment]
I can try with VPN off and I should not have the issue I imagine 🤞 
Thanks for digging, very surprising that the problem is actually upstream 😮

**Comment by SylEleuth** [comment]
OK. So for the `nm-no-connection-secure` I've just made it a symlink to `regular nm-no-connection`.
For stage animation I've tried to create something but without proper testing I'm not sure how it's going to look, and to be honest I'm not even sure how to test it. Can You look at it and tell me if You still have those errors?

**Comment by Diaoul** [comment]
I can confirm that I see the loading animations without VPN and I have no error in the console whatsoever.
Issue reported upstream ([here](https://gitlab.gnome.org/GNOME/network-manager-applet/-/issues/194))

**Comment by Diaoul** [comment]
Thanks a lot :rocket:

**Comment by SylEleuth** [comment]
That's great, I hope it looks ok. After some thoughts I think I will add lock symbol to all `-secure` icons. Not now but one day.
