### ISSUE TITLE
Flatpaks Steam, VLC, KeepassXC, Dolphin-Emulator,  do not take on icon theme in taskbar/tray.

### ISSUE THREAD

**Issue by LostWarriorr** [SylEleuth/gruvbox-plus-icon-pack#58]
I'm not entirely sure what the issue is here since firefox, thunderbird, and libreoffice work in the taskbar. 

I can see that the pack does include the flatpak icon names and i believe they are correct yet I have no idea why they won't take on the theme. I've tried putting in the GTK_ICON_THEME and QT_ICON_THEME (not sure on this one) variables and they all have access to my ~/.icons folder where the icons are present.

EDIT: VLC takes on the icon in the tray but not the taskbar

Distro: Debian sid
DE: XFCE

**Comment by SylEleuth** [comment]
I can see that some icons are not respected. E.g. KeepassXC uses original icon despite icon pack (any icon pack). Snap apps have similar problem where icons are hardcoded and you can't do nothing about it. Because icon shows in KDE and Gnome without issues that means it's XFCE4 or Flatpak problem.

**Comment by LostWarriorr** [comment]
Further investigations shows that there is some way to (partially) fix this. 

Fresh install of Mint XFCE has flatpak VLC following the icon theme but none of the others one listed do. Same Mint Icon theme on my main system and it doesn't work.

Not sure where the configuration difference is but its very strange.

**Comment by akarzim** [comment]
Here's how to make a Snap application respect the theme icon. Let's take the example of Joplin.

1. copy the Snap app `.desktop` file into your `~/.local` directory
   ```sh
   cp {/var/lib/snapd/desktop,~/.local/share}/applications/joplin-desktop_joplin-desktop.desktop
   ```
2. change the `Icon=` value by the theme icon's name in your local `.desktop` file
   ```diff
   - Icon=/snap/joplin-desktop/89/meta/gui/joplin-desktop.svg
   + Icon=joplin
   ```
3. enjoy it!
