### ISSUE TITLE
Icon Request: czkawka

### ISSUE THREAD

**Issue by genkieagle** [SylEleuth/gruvbox-plus-icon-pack#60]
Requesting icon for app "czkawka".

https://github.com/qarmin/czkawka
https://github.com/qarmin/czkawka/blob/master/data/icons/com.github.qarmin.czkawka.svg

This app uses name: "com.github.qarmin.czkawka.svg"

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/1607426a7dac1c2f5584d19d1e527324d7d7059e
