### ISSUE TITLE
Icon Request: lossless-cut

### ISSUE THREAD

**Issue by genkieagle** [SylEleuth/gruvbox-plus-icon-pack#61]
Requesting icon for app "lossless-cut".

https://github.com/mifi/lossless-cut
https://commons.wikimedia.org/wiki/File:LosslessCut_icon.svg

This app uses name: "losslesscut.svg"

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/1edb13e8e015c77e83919af446cb96028ce168d0
