### ISSUE TITLE
Icon Request: tsMuxer

### ISSUE THREAD

**Issue by genkieagle** [SylEleuth/gruvbox-plus-icon-pack#62]
Requesting icon for app "tsMuxer".

https://github.com/justdan96/tsMuxer
https://github.com/justdan96/tsMuxer/blob/master/tsMuxerGUI/images/icon.png

This app uses name: "tsMuxerGUI.svg"

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/d7d80c4bda2c42a5194d0e6528e58c24001111b3
