### ISSUE TITLE
Icon Request: openSUSE Tumbleweed

### ISSUE THREAD

**Issue by genkieagle** [SylEleuth/gruvbox-plus-icon-pack#63]
Requesting icon for distro "openSUSE Tumbleweed".

https://get.opensuse.org/tumbleweed/
https://github.com/openSUSE/distribution-logos/blob/main/Tumbleweed/square-hicolor.svg

openSUSE Tumbleweed uses icon name: "distributor-logo-Tumbleweed.svg"

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/23e5d5915d4512ab275163dc378d34e9ed15a69d
