### ISSUE TITLE
Trigger rally icon request

### ISSUE THREAD

**Issue by dimkauzh** [SylEleuth/gruvbox-plus-icon-pack#66]
Hey! Thank you for creating this icon pack, its amazing and i love it! I do have an icon request, of a kinda old game but its available in pretty much every Package manager. I thought of making it myself, but i have no experience in creating icons at all.

Game name: Trigger Rally
Website: [here](https://trigger-rally.sourceforge.io/)
Icon SVG: [here](https://sourceforge.net/p/trigger-rally/code/HEAD/tree/data/icon/trigger-rally-icons.svg)
The .desktop file: [here](https://sourceforge.net/p/trigger-rally/code/HEAD/tree/data/icon/trigger-rally.desktop)
Repository: [here](https://sourceforge.net/projects/trigger-rally/)

Thanks! If you have any questions feel free to ask, ill try to reply as soon as possible.

**Comment by SylEleuth** [comment]
Thank you for Your kind word. I've got something for You https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/2e1264ace5c016e7e7da40fdd521efd36160d90b.
