### ISSUE TITLE
Ventoy icon request

### ISSUE THREAD

**Issue by dimkauzh** [SylEleuth/gruvbox-plus-icon-pack#74]
Hi, i would like to request the icon for the Ventoy app (for flashing ventoy on usb's)

- Website: [here](https://www.ventoy.net/en/index.html)
- Icon(png): [here](https://www.ventoy.net/static/img/ventoy.png?v=1)

Thanks!

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/4948e2489370a0dc38ae6637a12579dbcaa1532e

**Comment by dimkauzh** [comment]
> [4948e24](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/4948e2489370a0dc38ae6637a12579dbcaa1532e)

Thanks!
