### ISSUE TITLE
[request] Add Icon for Zen Browser

### ISSUE THREAD

**Issue by redjohnsh** [SylEleuth/gruvbox-plus-icon-pack#77]
Zen is a new web browser based on firefox, similar to Arc. It would be nice to have a matching icon for it.

[Home page](https://zen-browser.app/)

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/7efc61fc5dd4effed93d3304b533298dec963852
