### ISSUE TITLE
nwg-look icon

### ISSUE THREAD

**Issue by wxn5211** [SylEleuth/gruvbox-plus-icon-pack#80]
GTK3 settings editor adapted to work in the wlroots environment
https://github.com/nwg-piotr/nwg-look

**Comment by SylEleuth** [comment]
Where is the issue?

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/e674ba1e6c69001f02b4dece5a5eea9f3a9b2052
