### ISSUE TITLE
[Request] new icons

### ISSUE THREAD

**Issue by olivertzeng** [SylEleuth/gruvbox-plus-icon-pack#81]
* [GoofCord](https://github.com/Milkshiift/GoofCord)
```
[Desktop Entry]
Name=GoofCord
Exec=goofcord --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto %U
Terminal=false
Type=Application
Icon=goofcord
StartupWMClass=GoofCord
Comment=Take control of your Discord experience with GoofCord – the highly configurable and privacy-minded discord client.
Categories=Network;
```
* [Btop](https://github.com/aristocratos/btop) (the logo only includes the B)
```
[Desktop Entry]
Type=Application
Version=1.0
Name=btop++
GenericName=System Monitor
Comment=Resource monitor that shows usage and stats for processor, memory, disks, network and processes
Icon=btop
Exec=btop
Terminal=true
Categories=System;Monitor;ConsoleOnly;
Keywords=system;process;task
```
* [KDiskMark](https://github.com/JonMagon/KDiskMark)
```
[Desktop Entry]
Name=KDiskMark
GenericName=KDiskMark
Comment=A disk drive benchmark tool
Keywords=benchmark;disk;
Exec=kdiskmark
Icon=kdiskmark
Terminal=false
StartupNotify=false
Type=Application
Categories=System;
```
* [Ryujinx](https://ryujinx.org/)
```
[Desktop Entry]
Version=1.0
Name=Ryujinx
Type=Application
Icon=Ryujinx
Exec=Ryujinx.sh %f
Comment=A Nintendo Switch Emulator
GenericName=Nintendo Switch Emulator
Terminal=false
Categories=Game;Emulator;
MimeType=application/x-nx-nca;application/x-nx-nro;application/x-nx-nso;application/x-nx-nsp;application/x-nx-xci;
Keywords=Switch;Nintendo;Emulator;
StartupWMClass=Ryujinx
PrefersNonDefaultGPU=true
```
* [Activate Linux](https://github.com/MrGlockenspiel/activate-linux) it has no icons and is optional
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Activate Linux
Comment=The \"Activate Windows\" watermark ported to Wayland
Exec=activate-linux
Icon=activate-linux
Terminal=false
StartupNotify=false
Categories=Application;
```
* [cpupower-gui](https://github.com/vagnum08/cpupower-gui)
```
[Desktop Entry]
Version=1.1
Name=cpupower-gui
GenericName=CPU frequency settings
Comment=Sets the frequency limits of the CPU
Exec=gapplication launch org.rnd2.cpupower_gui
Icon=org.rnd2.cpupower_gui
Terminal=false
Type=Application
DBusActivatable=true
StartupNotify=true
Categories=GNOME;GTK;Settings;HardwareSettings
Keywords=frequency;limits;
Actions=Performance;Balanced;

[Desktop Action Performance]
Name[el_GR]=Αλλαγή σε προφίλ επίδοσης
Name=Switch to Performance profile
Exec=gapplication launch org.rnd2.cpupower_gui Performance

[Desktop Action Balanced]
Name[el_GR]=Αλλαγή σε ισορροπημένο προφίλ
Name=Switch to Balanced profile
Exec=gapplication launch org.rnd2.cpupower_gui Balanced
```
* [kwatchgnupg](https://docs.kde.org/stable5/en/kleopatra/kwatchgnupg/index.html)
```
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Tobias Fella <tobias.fella@kde.org>
[Desktop Entry]
Version=1.5
Name=KWatchGnuPG
Exec=kwatchgnupg
Terminal=false
Icon=kwatchgnupg
Type=Application
Categories=System;
SingleMainWindow=true
```
* [NeoChat](https://apps.kde.org/neochat)
```
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2020 Tobias Fella <tobias.fella@kde.org>
[Desktop Entry]
Version=1.5
Name=NeoChat
Comment=Client for the Matrix protocol
MimeType=x-scheme-handler/matrix;
Exec=neochat %u
Terminal=false
Icon=org.kde.neochat
Type=Application
Categories=Network;InstantMessaging;
SingleMainWindow=true
```

**Comment by SylEleuth** [comment]
Btop is already there. You can't see it?
Same with Ryujinx, although I've added symlinks with name starting with capital **R**. It should be fine now. - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/61912280c38c3b97c1756846ccdb3acb6c9e7914
GoofCord - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f74e6a0d6462ac14bfd75effe8a22f749ff0a43a
KDiskMark - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/b91badf6cf64bfef08137d9b795c9ea5d04a771a
Activate Linux - if author didn't create an icon there is not much I can do except linking it to something else, in this case I just linked it to `tux.svg` - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f5363b4e3740ef56c6a1874fbc6abeecaa76009f
cpupower gui - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/bb07c9f506ece36409d850ccf490ab541b2b5d0a
KWatchGnuPG - no icon here, linked to `log-viewer.svg` - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/1615537de63e2e083f5e254592158fe86037db3c
NeoChat - https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/13f1f338086e1b3232affdfc4a13f95688a8a5f3

**Comment by olivertzeng** [comment]
> Btop is already there. You can't see it?

Maybe my own local icons isn't yet up to date? Sorry about that.

Anyways, that was damn fast! Thanks bro💕

**Comment by olivertzeng** [comment]
> Btop is already there. You can't see it? Same with Ryujinx, although I've added symlinks with name starting with capital **R**. It should be fine now. - [6191228](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/61912280c38c3b97c1756846ccdb3acb6c9e7914) GoofCord - [f74e6a0](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f74e6a0d6462ac14bfd75effe8a22f749ff0a43a) KDiskMark - [b91badf](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/b91badf6cf64bfef08137d9b795c9ea5d04a771a) Activate Linux - if author didn't create an icon there is not much I can do except linking it to something else, in this case I just linked it to `tux.svg` - [f5363b4](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/f5363b4e3740ef56c6a1874fbc6abeecaa76009f) cpupower gui - [bb07c9f](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/bb07c9f506ece36409d850ccf490ab541b2b5d0a) KWatchGnuPG - no icon here, linked to `log-viewer.svg` - [1615537](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/1615537de63e2e083f5e254592158fe86037db3c) NeoChat - [13f1f33](https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/13f1f338086e1b3232affdfc4a13f95688a8a5f3)

Oh wait it seems that i meant btop++ instead of btop
but should be the same icon
```
[Desktop Entry]
Type=Application
Version=1.0
Name=btop++
GenericName=System Monitor
Comment=Resource monitor that shows usage and stats for processor, memory, disks, network and processes
Icon=btop
Exec=btop
Terminal=true
Categories=System;Monitor;ConsoleOnly;
Keywords=system;process;task
```
