### ISSUE TITLE
[request] Add Zapzap Icon

### ISSUE THREAD

**Issue by dimkauzh** [SylEleuth/gruvbox-plus-icon-pack#82]
Zapzap, the linux Whatsapp client. It would be nice to have its icon.

[Github](https://github.com/rafatosta/zapzap)
[Desktop file](https://github.com/rafatosta/zapzap/blob/main/share/applications/com.rtosta.zapzap.desktop)
[Icon SVG](https://github.com/rafatosta/zapzap/blob/main/share/icons/com.rtosta.zapzap.svg)

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/9c0b7b0a5fee547b455357a962692451ab570f30
