### ISSUE TITLE
[request] Ente-Auth icon

### ISSUE THREAD

**Issue by dimkauzh** [SylEleuth/gruvbox-plus-icon-pack#83]
Some information:
- [Website](https://ente.io/auth/)
- [Repository](https://github.com/ente-io/ente/tree/main/auth)
- [Icon.png](https://github.com/ente-io/ente/blob/main/auth/assets/icons/auth-icon.png)
- [Icon.ico](https://github.com/ente-io/ente/blob/main/auth/assets/icons/auth-icon.ico)
- [Desktop file (from AUR)](https://aur.archlinux.org/cgit/aur.git/tree/ente_auth.desktop?h=ente-auth)

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/a19f6adb1e8cc6d5cd5130fc3977a3b75109b719
