### ISSUE TITLE
System icons missing on Ubuntu 22.04

### ISSUE THREAD

**Issue by matt1003** [SylEleuth/gruvbox-plus-icon-pack#84]
I have notices that some of my icons are missing on Ubuntu 22.04

Gnome defaults:

![Screenshot from 2024-10-07 22-39-45](https://github.com/user-attachments/assets/09221439-4ee3-4c9c-a936-3faff2b016d5)

Gruvbox-Plus-Dark:

![Screenshot from 2024-10-07 22-39-07](https://github.com/user-attachments/assets/1991d0f1-7177-4431-8be9-4d9ad01d9044)

**Comment by SylEleuth** [comment]
What's the file manager?

**Comment by matt1003** [comment]
It is using Nautilus Files:

![Screenshot from 2024-10-08 09-49-08](https://github.com/user-attachments/assets/d59a1848-7ad4-47cb-87f0-525624c5eec5)

https://apps.gnome.org/Nautilus/

Note: Icons are also missing from the Ubuntu Settings menu:

![Screenshot from 2024-10-08 09-49-55](https://github.com/user-attachments/assets/abdeaa03-e16e-4921-aad4-c49675dbcc7d)

**Comment by SylEleuth** [comment]
![files](https://github.com/user-attachments/assets/0154a67c-794b-4614-b230-0027d0013c2c)
That's how it looks on my side. Default gnome, only icons changes.
Also Your Ubuntu settings looks nothing like mine. You have to give me more information how You achieved that look. How You managed to use gruvbox icons there, because I still have default ones.

**Comment by matt1003** [comment]
Honestly, I have not done much. I am using the default Ubuntu 22.04 install. 

![Screenshot from 2024-10-09 07-42-53](https://github.com/user-attachments/assets/c04d5feb-0436-4666-808e-1bd9cbf71c8b)

I have done the following:

```
mkdir /home/$USER/work/
git clone https://github.com/SylEleuth/gruvbox-plus-icon-pack.git /home/$USER/work/gruvbox-plus-icon-pack
mkdir /home/$USER/.icons/
ln -s /home/$USER/work/gruvbox-plus-icon-pack/Gruvbox-Plus-Dark/ /home/$USER/.icons/
sudo apt install gnome-tweaks
```

Then used gnome-tweaks to configure the icons:

![Screenshot from 2024-10-09 09-09-31](https://github.com/user-attachments/assets/a98d214e-e3b4-473c-a4c8-2d75a05af05d)

I was also using the following theme:

https://github.com/TheGreatMcPain/gruvbox-material-gtk

And the dock-to-panel gnome extension, however disabling these have no effect.

Please let me know what other information you are looking for.

**Comment by SylEleuth** [comment]
I will install Ubuntu again, exact version You have. In the meantime can You download latest release and test with it?
