### ISSUE TITLE
[request] Icon for NoSQLBooster

### ISSUE THREAD

**Issue by matt1003** [SylEleuth/gruvbox-plus-icon-pack#87]
https://nosqlbooster.com/

nosqlbooster4mongo.desktop:
```
[Desktop Entry]
Name=NoSQLBooster for MongoDB
Exec=AppRun --no-sandbox %U
Terminal=false
Type=Application
Icon=nosqlbooster4mongo
StartupWMClass=NoSQLBooster for MongoDB
X-AppImage-Version=9.0.6
Comment=Essential Admin GUI for MongoDB
Categories=Development;
```

icons:

![nosqlbooster4mongo](https://github.com/user-attachments/assets/b208f8fe-ba1e-4821-996d-540ca2c37e8f)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/7a730eb7-cd2c-4076-afea-88b24489292e)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/30e66cdc-63c7-4faa-9725-6b5b4d64ad58)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/51666eab-87d1-47e6-97db-9b4f849e80cc)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/1b0e377d-1b9c-49a4-8bb2-5c0f5b67b9ff)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/06cd2799-e4c5-4b8b-a42f-cdb3bbf7d3bc)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/23cbf494-b137-4ebd-b3cf-7d7806fd2832)

![nosqlbooster4mongo](https://github.com/user-attachments/assets/31869047-cd68-4fc9-9bbb-86d62300660b)

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/b211cb406ec7f0a3e43267cd4feabf89d70c1ef0
