### ISSUE TITLE
[request] Icon for FortiClient

### ISSUE THREAD

**Issue by matt1003** [SylEleuth/gruvbox-plus-icon-pack#88]
https://www.fortinet.com/support/product-downloads

forticlient.desktop:
```
[Desktop Entry]
Version=1.0
Name=FortiClient
GenericName=Security Software
Comment=Endpoint Protection Suite
Exec=/opt/forticlient/gui/FortiClient-linux-x64/FortiClient
Icon=forticlient
Type=Application
Terminal=false
Categories=Utility;
```

icons:

![forticlient](https://github.com/user-attachments/assets/8345d3fd-8870-4db0-8478-ca76a275d7d0)

![forticlient](https://github.com/user-attachments/assets/6082d089-0102-4534-b5aa-3715c43ccb60)

![forticlient](https://github.com/user-attachments/assets/3b717e32-aed5-4b1b-9ab2-59d2bf80b2ca)

![forticlient](https://github.com/user-attachments/assets/51b32bdc-677c-4fcf-8872-76430d1c94df)

![forticlient](https://github.com/user-attachments/assets/ea4c4843-bc0a-4e4c-8318-f5541965e4db)

![forticlient](https://github.com/user-attachments/assets/1f15496c-29a2-4122-9515-61919d89959c)

![forticlient](https://github.com/user-attachments/assets/2c81d4e7-aa28-4092-afe3-aecfe8ef9ce2)

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/ab3b609c0a0ffb274ca27e2ebb6d67e17d7ffdaf
