### ISSUE TITLE
Request for some more icons

### ISSUE THREAD

**Issue by eugenialoli** [SylEleuth/gruvbox-plus-icon-pack#92]
Hello,
I'd like to request a few more apps and games icons. These are the things I use a lot and they don't have icons for. Thank you!

APPS: 

File renamer (Linux Mint app, installed by default)
ConvertAll
Warpinator (Mint)
BoxySVG (webapp)
PhotoPea (webapp)
Friction (www.friction.graphics, brand new app)
Drawing (Mint)
Matrix (Mint)
Liferea
Foliate
OnlyOffice
Library (Mint)
FreeTube
Hypnotix (Mint)
Celluloid (Mint)
Actions (Mint)
Gnome System Monitor (has the same icon as htop, so it's confusing)
Subsurface (Linus Torvalds' other app)
MeshLab 3D
Renoise
QCad
Pixelorama
Bitwig Studio
Reaper
Rosegarden
Presonus Studio One
Extension Manager
Denaro
Pinta
Design (Gnome CAD)
Jellyfin (web app)
Mastodon (web app)
Pixelfed (web app)
Lemmy (web app)
Viber (web app)
NewsFlash (Gnome RSS app)
QuietRSS
Flatseal

GAMES

LGeneral
LbreakoutHD
Powermanga
Tower Toppler
Xye
Li-Ri
FloboPuyo
Enigma
Opentransport Tycoon
LinCity NG
Warzone 2100
Freeciv
FreeCol
Freeorion
Flighgear
0AD
Opentyrian
Simutrans

Also, some icons were not changed when I installed the theme, even if the icon for these apps does exist, e.g. Gnumeric, and Dia (I'm on Linux Mint).

**Comment by SylEleuth** [comment]
Some of those icons are already there.
Webapps are web apps. `Apps` icons are for desktop applications.

Burying me with names won't work here. I know that a lot of icons are missing, but I'm not working on it full time, and nobody is paying me for it. If You want to make it easier for me pick up one name at the time, open a new issue and follow [this](https://github.com/SylEleuth/gruvbox-plus-icon-pack?tab=readme-ov-file#contribution) instructions. If You noticed that some icons do not work, do the same thing - pick up a name, open new issue and give me as much information as it's possible (system, DE, etc.)

**Comment by eugenialoli** [comment]
I understand. I will open new issues for each app, with links, and maybe a quick justification as to why it would be nice to have an icon for that app. I will only open issues for the most popular apps.

Also, is there a paypal address that I could donate? I would love to help out.
Unfortunately, I'm not good with digital art (I paint traditionally), but I could donate.

thanks!

**Comment by SylEleuth** [comment]
Thank You for Your offer but I'm not taking money for this project. I don't think it's worth anything especially when I do it mostly for myself.
