### ISSUE TITLE
Request: Foliate icon

### ISSUE THREAD

**Issue by eugenialoli** [SylEleuth/gruvbox-plus-icon-pack#93]
Foliate is a popular book reader (the two popular ones are Foliate and Calibre. Calibre already has an icon).
https://johnfactotum.github.io/foliate/

**Comment by SylEleuth** [comment]
It's already there. I've just tested the app and it works as intended.
Remember that if You install apps through snap You won't see my icons (or any icons from any pack). I'm not sure about flathub (sometimes it works).

**Comment by eugenialoli** [comment]
I can't find foliate in my Gruvbox-Plus-Dark/apps/scalable/ folder. Neither it was found automatically by the system to replace its default icon (foliate was installed as a .deb file from the official repo).

**Comment by SylEleuth** [comment]
How did You install icon pack?

**Comment by SylEleuth** [comment]
A lot happened since that time. I recommend to clone repository and link it to that folder. I make changes/add new icons everyday. Otherwise You'd have to wait for a new release (a month or two).

**Comment by eugenialoli** [comment]
I just did so on a brand new installation of Mint. I got the master from git and installed under ~/.icons/. Foliate doesn't get picked up by the change of theming to gruvbox. I have to change it manually.

**Comment by SylEleuth** [comment]
I'm not sure I understood but if You do it correctly You should be able to easily pull any changes any time.

**Comment by eugenialoli** [comment]
I didn't pull the git, just downloaded the zip file of it (the website allows you to download the latest version as zip). I downloaded it after you made the change to put foliate.svg under scalable too. For some reason, it still doesn't work...

**Comment by SylEleuth** [comment]
I downloaded and used it and it worked as intended. Please show me .desktop file for the app.

**Comment by eugenialoli** [comment]
I'm including both foliate and gnumeric desktop files (both don't pick up the icon automatically):

[Archive 2.zip](https://github.com/user-attachments/files/17476228/Archive.2.zip)

**Comment by SylEleuth** [comment]
Both icons are there. I'm not sure what else I can do.
