### ISSUE TITLE
OnlyOffice

### ISSUE THREAD

**Issue by eugenialoli** [SylEleuth/gruvbox-plus-icon-pack#95]
OnlyOffice is a rather new open source office suite. It has better compatibility with MS Office formats than LlibreOffice, plus a PDF editor like Adobe's.
https://www.onlyoffice.com/

**Comment by SylEleuth** [comment]
It was there partially (`16`), I've added scalable.
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/bc29a7472c9ec87a2eac082fe479d1a92eaa9183
