### ISSUE TITLE
Icon Request, Discord + Optimus GPU Switcher Appindicator Icons

### ISSUE THREAD

**Issue by 0verEngineer** [SylEleuth/gruvbox-plus-icon-pack#99]
Hey, thanks a lot for this project, i noticed 2 icons in my Appindicator that don't have/use gruvbox-plus icons:
- Discord
- Optimus GPU Switcher

Optimus GPU Switcher has variable Icons so i don't know if this is easily doable but it would be great.

**Comment by SylEleuth** [comment]
Discord is already in the pack. How did You install it?
Can You share a link to Optimus GPU Switcher?

**Comment by 0verEngineer** [comment]
I have Discord installed as Flatpak

https://github.com/enielrodriguez/optimus-gpu-switcher

![image](https://github.com/user-attachments/assets/7d082edc-85ea-4dbf-9001-a3ad6763d4a3)

**Comment by SylEleuth** [comment]
Oh, it's about taskbar. I thought You were talking about apps. In that case Discord has hardcoded icons so You can't replace them. I'm using `Kdocker` so You could try that.
`Optimus GPU Switcher` icons are `png`. What You can do is change the code and path to the proper icons in the pack. In theory it should work but You would have to test that. Not all icons are there so let me know if it works and which icons You would need.
